services:
  sqlserver:
    image: mcr.microsoft.com/azure-sql-edge
    container_name: sqlserver
    environment:
      - SA_PASSWORD=${SA_PASSWORD}
      - ACCEPT_EULA=${ACCEPT_EULA}
    ports:
      - "1433:1433"
    volumes:
      - sqlserverdata:/var/opt/mssql
volumes:
  sqlserverdata:
